## Coding Exercise #0102

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3

array([3, 6, 9])

In [7]:
b + b

array([2, 4, 6])

In [8]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
a-b

array([-3, -3, -3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [14]:
x = np.array([0, 1, 2, 3, 4, 5])

In [15]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [16]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [19]:
type(np.sqrt)

numpy.ufunc

In [20]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [21]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [22]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.median(a)

5.0

In [24]:
np.sum(a)

5485

In [26]:
np.round(np.var(a),2)

8.19

In [27]:
np.round(np.mean(a),2)

5.48

In [31]:
np.round(np.std(a),2) #2 numbers after float of std

2.86

In [32]:
np.max(a)

10

In [33]:
np.min(a)

1

#### 1.5. Statistical methods of NumPy arrays:

In [34]:
x=np.arange(1,11)

In [35]:
x.sum()

55

In [36]:
x.mean()

5.5

In [37]:
x.std()

2.8722813232690143

In [38]:
x.var()

8.25

In [50]:
x.cumsum() # Return cumulative sum over DataFrame axis.

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [43]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
print(y.mean(axis=0)) #Mean of lines 

[4. 5. 6.]


In [46]:
print(y.mean(axis=1)) #Mean of column 

[2. 5. 8.]


In [51]:
z = np.random.randint(10,size=1000)

In [52]:
z.max()

9

In [53]:
z.min()

0

In [54]:
(z > 5).sum()

402

In [56]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [59]:
a.argmax()

4

In [60]:
a.argmin()

1

In [67]:
np.random.seed(123) # to have always same results with random, we use also randomstate 
a=np.random.randint(1,11)
a

3

In [69]:
while True:
    num=np.random.randint(1,11)
    print(num)
    if (num==10):
        break
np.__version__

7
2
1
2
10


'1.20.3'