Array Transposition

In [2]:
import numpy as np

In [3]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr=np.random.randn(6,3)
arr

array([[-0.27760184, -1.3099697 ,  0.17234172],
       [-0.48411509,  0.74491846,  0.1325318 ],
       [-1.24960263, -1.23056062,  0.81485636],
       [-0.16749971, -1.58841275,  0.22633039],
       [-1.65865002,  0.50040997,  0.18282194],
       [-1.01686986,  1.33263654,  1.10380339]])

In [6]:
np.dot(arr.T, arr)

array([[ 5.68613728, -0.37832875, -2.59382195],
       [-0.37832875,  8.33458892,  0.07318137],
       [-2.59382195,  0.07318137,  2.01428846]])

In [7]:
arr=np.arange(16).reshape(2,2,4)

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [10]:
arr.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])